### ISSUE TITLE
Special syntax to allow arbitrary line splitting

### ISSUE THREAD

**Issue by kvaleev** [foliant-docs/foliantcontrib.multilinetables#1]
As this preprocessor converts long pipe tables to multiline ones, it'll be great to have a hack to place a command for line split on pipe tables. When it is converted to multiline table the command will become just a regular new line.

Which exact command to use as a line split in pipe tables can be chosen in preprocessor config.

**Comment by apkraft** [comment]
Released in 1.1.2 version.
